# Generated by Django 6.1.1 on 2026-10-07 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments_app', '0001_initial'),
        ('tasks_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks_app.tasks'),
        ),
    ]
